"""add article

Revision ID: 2b6d7327c92b
Revises: 064197f7560c
Create Date: 2024-07-15 18:02:58.914623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6d7327c92b'
down_revision: Union[str, None] = '064197f7560c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_extension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_extension_id'), 'user_extension', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_extension_id'), table_name='user_extension')
    op.drop_table('user_extension')
    # ### end Alembic commands ###
